function [codeVersion, reply] = about_displayCounts_private()
%function [codeVersion, reply] = about_displayCounts_private()
% codeVersion: version number in floating point xx.yyy where X is major & yyy is minor
%reply: string including some text, the date & time of creation & the above version number
% Note: this function is generated by "makeabout_diag" & therefore
%this file should not be editted.

codeVersion = 0.000000;
if codeVersion
  reply = sprintf('displayCounts Version %.3f (Debug) created 22-Feb-2011 21:14:49.', codeVersion);
else % if codeVersion
  reply = sprintf('displayCounts created  (Debug)22-Feb-2011 21:14:49.');
end % if codeVersion
