function [codeVersion, reply] = about_installELogger_private()
%function [codeVersion, reply] = about_installELogger_private()
% codeVersion: version number in floating point xx.yyy where X is major & yyy is minor
%reply: string including some text, the date & time of creation & the above version number
% Note: this function is generated by "makeabout_diag" & therefore
%this file should not be editted.

codeVersion = 0.000000;
if codeVersion
  reply = sprintf('installELogger Version %.3f (Debug) created 12-Jan-2012 11:37:35.', codeVersion);
else % if codeVersion
  reply = sprintf('installELogger created  (Debug)12-Jan-2012 11:37:35.');
end % if codeVersion
