function [codeVersion, reply] = about_dispNghbrhdSmry_demo_priv()
%function [codeVersion, reply] = about_dispNghbrhdSmry_demo_priv()
% codeVersion: version number in floating point xx.yyy where X is major & yyy is minor
%reply: string including some text, the date & time of creation & the above version number
% Note: this function is generated by "makeabout_diag" & therefore
%this file should not be editted.

codeVersion = 0.000000;
if codeVersion
  reply = sprintf('dispNghbrhdSmry_demo Version %.3f (Debug) created 27-Dec-2011 22:41:42.', codeVersion);
else % if codeVersion
  reply = sprintf('dispNghbrhdSmry_demo created  (Debug)27-Dec-2011 22:41:42.');
end % if codeVersion
